### ISSUE TITLE
When I open Obsidian pop up "Nativian not found"

### ISSUE THREAD

**Issue by matiasdiez** [Faetu/nativian#1]
Hi,

I installed the script. This create a desktop icon (and i still have my own from AppImage). When i click to open the new Nativian desktop icon prompt a windows that says "Nativian not found" in the title, and ask "Its seem that nativian is not installed, Want to install it", I click yes, another windows with title "Downloading obsidian" and another of extracting and then disappear. If I open again the process repeat.

Sorry my english, is not my native tong.

I am running Ubuntu 21.10. My Obsidian is installed in /opt/applications.

**Comment by Faetu** [comment]
Hi @matiasdiez 

sry for the late response.

> Sorry my english, is not my native tong.

Np, I understood what you write, and btw, english is not my native language either.

Could you check these three points pls:
1. Does the directory `~/.local/share/nativian/` exists and is it empty? 
2. Have you installed nodejs+npm?
if not:
```bash
sudo apt install nodejs
sudo apt install npm
```
3. Have you installed `appimagetool`?
if not:
```bash
sudo wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
sudo chmod +x /usr/local/bin/appimagetool
```
source: [Get appimage-builder](https://appimage-builder.readthedocs.io/en/latest/intro/install.html#debian-ubuntu)

**Comment by Faetu** [comment]
No response => Closed

**Comment by matiasdiez** [comment]
Really sorry my late response. Its work, this time in Ubuntu 22.04. Thank you!!
